version: 2

project_name: go-switcher

before:
  hooks:
    - go mod tidy

builds:
  - id: switcher
    main: ./cmd/switcher
    binary: switcher
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: binaries
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: checksums.txt

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: mrtuuro
    name: go-switcher

brews:
  - name: go-switcher
    repository:
      owner: mrtuuro
      name: homebrew-go-switcher
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/mrtuuro/go-switcher
    description: Switch and install Go toolchains with local/global scope and TUI
    license: MIT
    commit_author:
      name: go-switcher-bot
      email: 183410257+mrtuuro@users.noreply.github.com
    install: |
      bin.install "switcher"
    test: |
      system "#{bin}/switcher", "help"
    caveats: |
      Add switcher shim directory to PATH for go/gofmt/golangci-lint routing:
        export PATH="$HOME/.switcher/bin:$PATH"
